---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker
  - device: /dev/vdb
    mountpoint: /data

# CouchDB and GitHUB configuration
CouchDBVERSION: '3.2.1'
couchdb_user: admin
couchdb_pass: admin
couchdb_nodes: 3
cookie: '############'
uuid: ################
mrc_workdir: /home/ubuntu/CCCA2
git_repo: /home/ubuntu/CCCA2/CCC2022S1A2-group43
docker_proxy_settings: "{\"proxies\":{\"default\":{\"httpProxy\":\"http://wwwproxy.unimelb.edu.au:8000\",\"httpsProxy\":\"http://wwwproxy.unimelb.edu.au:8000\",\"noProxy\":\"localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbounre.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au\"}}}"


# Proxy
proxy_env:
  no_proxy: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au
  HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  http_proxy: http://wwwproxy.unimelb.edu.au:8000/
  https_proxy: http://wwwproxy.unimelb.edu.au:8000/
